# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('calls', '0001_initial'),
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('applies_to_expression', models.BooleanField(default=True, verbose_name='Aplica a Expresiones')),
                ('applies_to_proposal', models.BooleanField(default=True, verbose_name='Aplica a Propuestas')),
                ('calls', models.ManyToManyField(blank=True, related_name='evaluation_templates', to='calls.call', verbose_name='Convocatorias Aplicables')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Evaluacion',
                'verbose_name_plural': 'Plantillas de Evaluacion',
                'db_table': 'evaluation_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('target_object_id', models.PositiveIntegerField(verbose_name='ID del Objetivo')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuación Total')),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Puntuación Máxima Posible')),
                ('submission_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('is_positive', models.BooleanField(default=False, verbose_name='Evaluación positiva')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validada por coordinador')),
                ('coordinator_notes', models.TextField(blank=True, verbose_name='Notas del coordinador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='Evaluador')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado')),
                ('target_content_type', models.ForeignKey(limit_choices_to={'model__in': ['expression', 'proposal']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Objetivo')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.evaluationtemplate', verbose_name='Plantilla de Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluation',
                'ordering': ['-submission_datetime'],
                'unique_together': {('target_content_type', 'target_object_id', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='evaluations.evaluationtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Categoría de Plantilla',
                'verbose_name_plural': 'Categorías de Plantilla',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('field_type', models.CharField(choices=[('text', 'Texto largo'), ('short_text', 'Texto corto'), ('number', 'Número'), ('boolean', 'Sí/No'), ('dropdown', 'Desplegable (Opciones Estáticas)'), ('dynamic_dropdown', 'Desplegable (Opciones Dinámicas)'), ('radio', 'Opción múltiple')], default='text', max_length=20, verbose_name='Tipo de Campo')),
                ('options', models.JSONField(blank=True, help_text="Opciones para dropdown o radio (ej: ['Sí', 'No', 'Parcialmente'])", null=True, verbose_name='Opciones Estaticas')),
                ('source_model', models.CharField(blank=True, choices=[('geo.Country', 'País'), ('common.Status', 'Estado'), ('thematic_axes.ThematicAxis', 'Eje Temático'), ('budgets.BudgetPeriod', 'Período de Presupuesto'), ('budgets.BudgetCategory', 'Categoría de Presupuesto'), ('institutions.Institution', 'Institución'), ('intersectionality.IntersectionalityScope', 'Ámbito de Interseccionalidad'), ('people.Person', 'Persona'), ('strategic_effects.StrategicEffect', 'Efecto Estratégico')], help_text="Si se selecciona, carga opciones desde este modelo. (Ignorar para 'Opciones Estaticas')", max_length=100, null=True, verbose_name='Modelo de Origen')),
                ('max_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Puntuación Máxima')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.templatecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de Plantilla',
                'verbose_name_plural': 'Ítems de Plantilla',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Valor')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='evaluations.evaluation', verbose_name='Evaluación')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.templateitem', verbose_name='Ítem Evaluado')),
            ],
            options={
                'verbose_name': 'Respuesta de Evaluación',
                'verbose_name_plural': 'Respuestas de Evaluación',
                'unique_together': {('evaluation', 'item')},
            },
        ),
    ]
