# Generated by Django 5.2.5 on 2025-10-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='options',
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='source_model',
            field=models.CharField(blank=True, choices=[('geo.Country', 'País'), ('common.Status', 'Estado'), ('thematic_axes.ThematicAxis', 'Eje Temático'), ('budgets.BudgetPeriod', 'Período de Presupuesto'), ('budgets.BudgetCategory', 'Categoría de Presupuesto'), ('institutions.Institution', 'Institución'), ('intersectionality.IntersectionalityScope', 'Ámbito de Interseccionalidad'), ('people.Person', 'Persona'), ('strategic_effects.StrategicEffect', 'Efecto Estratégico')], max_length=100, null=True, verbose_name='Modelo de Origen'),
        ),
        migrations.CreateModel(
            name='TemplateItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('display_text', models.CharField(max_length=200, verbose_name='Texto a mostrar')),
                ('score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Puntuación asociada')),
                ('source_object_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto si proviene de source_model', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='evaluations.templateitem', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Opción de Ítem',
                'verbose_name_plural': 'Opciones de Ítem',
                'ordering': ['item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='evaluations.templatecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría de Plantilla',
                'verbose_name_plural': 'Subcategorías de Plantilla',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='templateitem',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.templatesubcategory', verbose_name='Subcategoría'),
            preserve_default=False,
        ),
    ]
