# Generated by Django 5.2.5 on 2025-09-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_templateitem_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateitem',
            name='source_model',
            field=models.CharField(blank=True, choices=[('geo.Country', 'País'), ('common.Status', 'Estado'), ('thematic_axes.ThematicAxis', 'Eje Temático'), ('budgets.BudgetPeriod', 'Período de Presupuesto'), ('budgets.BudgetCategory', 'Categoría de Presupuesto'), ('institutions.Institution', 'Institución'), ('intersectionality.IntersectionalityScope', 'Ámbito de Interseccionalidad'), ('people.Person', 'Persona'), ('strategic_effects.StrategicEffect', 'Efecto Estratégico')], help_text="Si se selecciona, carga opciones desde este modelo. (Ignorar para 'Opciones Estaticas')", max_length=100, null=True, verbose_name='Modelo de Origen'),
        ),
    ]
