# Generated by Django 5.2.5 on 2025-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationtemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
