# Generated by Django 5.2.5 on 2025-10-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_remove_templateitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecategory',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='templatesubcategory',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Nombre'),
        ),
    ]
