# Generated by Django 5.2.5 on 2025-10-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_templatecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateitem',
            unique_together={('subcategory', 'question')},
        ),
    ]
