# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('field_type', models.CharField(choices=[('text', 'Texto largo'), ('short_text', 'Texto corto'), ('number', 'Número'), ('boolean', 'Sí/No'), ('dropdown', 'Desplegable (Opciones Estáticas)'), ('dynamic_dropdown', 'Desplegable (Opciones Dinámicas)'), ('radio', 'Opción múltiple')], default='text', max_length=20, verbose_name='Tipo de Campo')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Opciones Estaticas')),
                ('source_model', models.CharField(blank=True, choices=[('geo.Country', 'País'), ('common.Status', 'Estado'), ('thematic_axes.ThematicAxis', 'Eje Temático'), ('budgets.BudgetPeriod', 'Período de Presupuesto'), ('budgets.BudgetCategory', 'Categoría de Presupuesto'), ('institutions.Institution', 'Institución'), ('intersectionality.IntersectionalityScope', 'Ámbito de Interseccionalidad'), ('people.Person', 'Persona'), ('strategic_effects.StrategicEffect', 'Efecto Estratégico')], max_length=100, null=True, verbose_name='Modelo de Origen')),
                ('target_category', models.CharField(choices=[('expression', 'Expresion de Interes'), ('proposal', 'Propuesta Completa')], help_text='Para que tipo de formulario se usa esta pregunta', max_length=20, verbose_name='Categoria Objetivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_required', models.BooleanField(default=True, verbose_name='Requerida')),
            ],
            options={
                'verbose_name': 'Pregunta Compartida',
                'verbose_name_plural': 'Preguntas Compartidas',
                'db_table': 'shared_question',
                'ordering': ['target_category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ProponentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calls.call', verbose_name='Convocatoria')),
            ],
            options={
                'verbose_name': 'Formulario del Proponente',
                'verbose_name_plural': 'Formularios del Proponente',
                'db_table': 'proponent_form',
            },
        ),
        migrations.CreateModel(
            name='ProponentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Valor')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='expressions.expression', verbose_name='Expresión de Interés')),
                ('shared_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proponent_forms.sharedquestion', verbose_name='Pregunta Compartida')),
            ],
            options={
                'verbose_name': 'Respuesta del Proponente',
                'verbose_name_plural': 'Respuestas del Proponente',
                'db_table': 'proponent_response',
                'unique_together': {('expression', 'shared_question')},
            },
        ),
        migrations.CreateModel(
            name='ProponentFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('order', models.PositiveBigIntegerField(default=0, verbose_name='Orden')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='proponent_forms.proponentform', verbose_name='Formulario')),
                ('shared_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proponent_forms.sharedquestion', verbose_name='Pregunta Compartida')),
            ],
            options={
                'verbose_name': 'Pregunta del Formulario',
                'verbose_name_plural': 'Preguntas del Formulario',
                'db_table': 'proponent_form_question',
                'ordering': ['order'],
                'unique_together': {('form', 'shared_question')},
            },
        ),
    ]
