# Generated by Django 5.2.5 on 2025-10-15 23:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proponentresponse',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Puntuación derivada'),
        ),
        migrations.CreateModel(
            name='SharedQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('display_text', models.CharField(max_length=200, verbose_name='Texto a mostrar')),
                ('score', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, verbose_name='Puntuación asociada (opcional)')),
                ('shared_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_set', to='proponent_forms.sharedquestion', verbose_name='Pregunta Compartida')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta Compartida',
                'verbose_name_plural': 'Opciones de Pregunta Compartida',
                'ordering': ['shared_question', 'id'],
            },
        ),
    ]
