# Generated by Django 5.2.5 on 2025-10-05 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0002_alter_expression_primary_institution'),
        ('proponent_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponentresponse',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='expressions.expression', verbose_name='Expresión de Interés'),
        ),
    ]
