# Generated by Django 5.2.5 on 2025-09-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquestion',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto largo'), ('short_text', 'Texto corto'), ('number', 'Número'), ('boolean', 'Sí/No'), ('dropdown', 'Desplegable (Opciones Estáticas)'), ('dynamic_dropdown', 'Desplegable (Opciones Dinámicas)'), ('radio', 'Opción múltiple')], default='text', max_length=20, verbose_name='Tipo de Campo'),
        ),
    ]
