# Generated by Django 5.2.5 on 2025-10-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent_forms', '0002_proponentresponse_score_sharedquestionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de Pregunta',
                'verbose_name_plural': 'Categorías de Pregunta',
                'db_table': 'shared_question_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sharedquestion',
            options={'ordering': ['target_category', 'category__order', 'question'], 'verbose_name': 'Pregunta Compartida', 'verbose_name_plural': 'Preguntas Compartidas'},
        ),
        migrations.AddField(
            model_name='sharedquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='proponent_forms.sharedquestioncategory', verbose_name='Categoría'),
        ),
    ]
