# Generated by Django 5.2.5 on 2025-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent_forms', '0003_sharedquestioncategory_alter_sharedquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquestioncategory',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
