# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Convocatoria')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('opening_datetime', models.DateTimeField(db_index=True, verbose_name='Fecha de Apertura')),
                ('closing_datetime', models.DateTimeField(db_index=True, verbose_name='Fecha de Cierre')),
                ('coordinator', models.ForeignKey(blank=True, help_text='Usuario responsable de gestionar esta convocatoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_calls', to='accounts.customuser', verbose_name='Coordinador')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, help_text='Estado actual de la convocatoria (ej. Abierta, Cerrada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='common.status', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'db_table': 'calls',
                'ordering': ['-opening_datetime'],
            },
        ),
    ]
