# Generated by Django 5.2.5 on 2025-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Titulo'),
        ),
    ]
