# Generated by Django 5.2.5 on 2025-09-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='name',
            field=models.CharField(choices=[('S', 'Pequeña'), ('M', 'Mediana'), ('B', 'Grande')], max_length=1, unique=True, verbose_name='Escala'),
        ),
    ]
