# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thematic_axes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('thematic_axis', models.ForeignKey(help_text='Eje temático al que pertenece este efecto estratégico', on_delete=django.db.models.deletion.PROTECT, to='thematic_axes.thematicaxis', verbose_name='Eje Temático')),
            ],
            options={
                'verbose_name': 'Efecto Estrategico',
                'verbose_name_plural': 'Efectos Estrategicos',
                'db_table': 'strategic_effect',
                'ordering': ['thematic_axis__name', 'name'],
            },
        ),
    ]
