# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Rol')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(blank=True, help_text='Grupo de Permisos de Django asociado a este rol', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Grupo de Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Por favor, ingrese un numero de telefono valido (por ejemplo, +57(601)1234444, +1 555-123-4567 o (44) 20 7946 0958).', regex='^\\+?[\\d\\s\\-\\(\\)]{9,17}$')])),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts_user_groups', related_query_name='accounts_user', to='auth.group')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='people.person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts_user_permissions', related_query_name='acounts_user', to='auth.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='Rol')),
            ],
            options={
                'db_table': 'accounts_user',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_active_role_name'),
        ),
    ]
