# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Tipo de Experiencia',
                'verbose_name_plural': 'Tipos de Experiencia',
                'db_table': 'experience_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLeaderExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('description', models.TextField(verbose_name='Descripción de la Experiencia')),
                ('academic_title', models.CharField(max_length=100, verbose_name='Título Académico')),
                ('current_position', models.CharField(max_length=100, verbose_name='Cargo Actual')),
                ('experience_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.experiencetype', verbose_name='Tipo de Experiencia')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expressions.expression', verbose_name='Expresión de Interés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='Usuario (Líder del Proyecto)')),
            ],
            options={
                'verbose_name': 'Experiencia del Líder del Proyecto',
                'verbose_name_plural': 'Experiencias del Líder del Proyecto',
                'db_table': 'project_leader_experience',
                'ordering': ['expression__project_title', 'user__person__first_name', 'experience_type'],
                'unique_together': {('expression', 'user', 'experience_type')},
            },
        ),
    ]
