# Generated by Django 5.2.5 on 2025-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAntecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización')),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Financiado')),
                ('funding_source', models.CharField(max_length=100, verbose_name='Fuente de Financiamiento')),
                ('outcomes', models.TextField(verbose_name='Resultados o Impactos')),
                ('url', models.URLField(blank=True, verbose_name='URL de Evidencia')),
                ('institutions', models.ManyToManyField(related_name='project_antecedents', to='institutions.institution', verbose_name='Instituciones Participantes')),
            ],
            options={
                'verbose_name': 'Proyecto Antecedente',
                'verbose_name_plural': 'Proyectos Antecedentes',
                'db_table': 'project_antecedent',
                'ordering': ['-end_date', 'title'],
            },
        ),
    ]
