# Generated by Django 5.2.5 on 2025-10-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('expression_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expressions.expression')),
                ('budget_breakdown', models.TextField(help_text='Detalles de asignación de fondos por actividad', verbose_name='Desglose Presupuestario')),
                ('implementation_plan', models.TextField(help_text='Fases, cronograma, hitos', verbose_name='Plan de Implementación')),
                ('risk_analysis', models.TextField(help_text='Riesgos identificados y planes de mitigación', verbose_name='Análisis de Riesgos')),
                ('sustainability_plan', models.TextField(help_text='Cómo se mantendrá el proyecto después del financiamiento', verbose_name='Plan de Sostenibilidad')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'db_table': 'proposal',
            },
            bases=('expressions.expression',),
        ),
    ]
