# Generated by Django 5.2.5 on 2025-10-02 20:56
from django.utils import timezone
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('geo', '0001_initial'),
        ('institutions', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='budget_breakdown',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='implementation_plan',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='risk_analysis',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='sustainability_plan',
        ),
        migrations.AddField(
            model_name='proposal',
            name='communication_strategy',
            field=models.TextField(blank=True, help_text='Máximo 100 palabras', max_length=400, verbose_name='Estrategia de comunicación'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='community_country',
            field=models.ForeignKey(blank=True, help_text='País de la comunidad involucrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_community_country', to='geo.country', verbose_name='País donde se desarrolla la comunidad'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='community_description',
            field=models.TextField(blank=True, help_text='Descripción de la comunidad y su contexto', verbose_name='Comunidad y país'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='context_problem_justification',
            field=models.TextField(blank=True, help_text='Máximo 400 palabras', max_length=1600, verbose_name='Contexto, problema y justificación'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Número de meses', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración del proyecto'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='equity_inclusion',
            field=models.TextField(blank=True, help_text='Máximo 250 palabras', max_length=1000, verbose_name='Equidad, género, interseccionalidad e inclusión'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='methodology_analytical_plan_ethics',
            field=models.TextField(blank=True, help_text='Máximo 1500 palabras', max_length=6000, verbose_name='Metodología, planeamiento analítico y aspectos éticos'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='partner_institutions',
            field=models.ManyToManyField(blank=True, related_name='proposals_as_partner', to='institutions.institution', verbose_name='Nombre y país de las instituciones aliadas'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='principal_research_experience',
            field=models.TextField(blank=True, help_text='Máximo 250 palabras', max_length=1000, verbose_name='Experiencia en investigación del Investigador/a Principal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='project_location',
            field=models.ForeignKey(blank=True, help_text='País principal de implementación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_as_project_location', to='geo.country', verbose_name='País donde se desarrollará el proyecto'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='research_team',
            field=models.TextField(blank=True, help_text='Máximo 900 palabras', max_length=3600, verbose_name='Equipo de investigación'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='risk_analysis_mitigation',
            field=models.TextField(blank=True, help_text='Máximo 200 palabras', max_length=800, verbose_name='Riesgos y plan de mitigación de riesgos'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='specific_objectives',
            field=models.TextField(blank=True, help_text='Máximo 200 palabras', max_length=800, verbose_name='Objetivos específicos'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='summary',
            field=models.TextField(blank=True, help_text='Síntesis descriptiva de la propuesta (máximo 250 palabras)', max_length=1000, verbose_name='Resumen'),
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion', default=timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion', default=timezone.now)),
                ('file', models.FileField(help_text='Sube archivos como PDF, DOCX. Máximo 10MB.', upload_to='proposal_documents/%Y/%m/%d/', verbose_name='Archivo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('document_type', models.CharField(choices=[('timeline', 'Cronograma'), ('budget', 'Presupuesto'), ('commitment', 'Carta de Compromiso')], max_length=50, verbose_name='Tipo de Documento')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_documents', to='proposals.proposal', verbose_name='Propuesta')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento de Propuesta',
                'verbose_name_plural': 'Documentos de Propuesta',
                'db_table': 'proposal_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='budget_document',
            field=models.ForeignKey(blank=True, help_text='Archivo adjunto (PDF, DOCX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_budget', to='proposals.proposaldocument', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='partner_institution_commitments',
            field=models.ManyToManyField(blank=True, related_name='proposals_for_commitments', to='proposals.proposaldocument', verbose_name='Cartas de compromiso institucional'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='timeline_document',
            field=models.ForeignKey(blank=True, help_text='Archivo adjunto (PDF, DOCX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_timeline', to='proposals.proposaldocument', verbose_name='Cronograma'),
        ),
    ]
