# Generated by Django 5.2.5 on 2025-10-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_phone_number'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='linked_institution',
            field=models.ForeignKey(blank=True, help_text='Solo si el documento es específico para una institución (ej: carta de compromiso)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution', verbose_name='Institución Asociada'),
        ),
    ]
