# Generated by Django 5.2.5 on 2025-10-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposaldocument_linked_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='general_objective_override',
            field=models.TextField(blank=True, help_text='Si se especifica, sobrescribe el objetivo general de la expresión.', null=True),
        ),
    ]
