# Generated by Django 5.2.5 on 2025-10-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposal_budget_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
