# Generated by Django 5.2.5 on 2025-10-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('proposals', '0003_alter_proposaldocument_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.ForeignKey(default=1, help_text='Estado del ciclo de vida de la propuesta (Borrador, Enviada, Aprobada, etc.)', on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado de la Propuesta'),
            preserve_default=False,
        ),
    ]
