# Generated by Django 5.2.5 on 2025-10-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_general_objective_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='research_team',
        ),
    ]
