# Generated by Django 5.2.5 on 2025-10-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_remove_proposal_research_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='community_organizations',
        ),
    ]
