# Generated by Django 5.2.5 on 2025-10-05 05:57

import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaldocument',
            name='file',
            field=models.FileField(help_text='Sube archivos como PDF, DOCX. Máximo 10MB.', max_length=500, upload_to=proposals.models.proposal_file_upload_path, verbose_name='Archivo'),
        ),
    ]
