# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('number_of_members', models.PositiveIntegerField(verbose_name='Número de Miembros')),
                ('contact_person_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Persona de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=17, verbose_name='Teléfono de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de Contacto')),
            ],
            options={
                'verbose_name': 'Organización Comunitaria (CBO)',
                'verbose_name_plural': 'Organizaciones Comunitarias (CBOs)',
                'db_table': 'cbo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CBOAntecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('funding_source', models.CharField(blank=True, max_length=100, verbose_name='Fuente de Financiamiento')),
                ('outcomes', models.TextField(verbose_name='Resultados')),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='cbo.cbo', verbose_name='CBO')),
            ],
            options={
                'verbose_name': 'Antecedente de CBO',
                'verbose_name_plural': 'Antecedentes de CBO',
                'db_table': 'cbo_antecedent',
                'ordering': ['-year', 'project_name'],
            },
        ),
        migrations.CreateModel(
            name='CBORelevantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('predefined_role', models.CharField(blank=True, choices=[('president', 'Presidente'), ('vice_president', 'Vicepresidente'), ('coordinator', 'Coordinador'), ('treasurer', 'Tesorero'), ('secretary', 'Secretario'), ('member', 'Miembro')], max_length=20, null=True, verbose_name='Rol Predefinido')),
                ('custom_role', models.CharField(blank=True, max_length=50, verbose_name='Rol Personalizado')),
                ('person_name', models.CharField(max_length=100, verbose_name='Nombre de la Persona')),
                ('contact_phone', models.CharField(blank=True, max_length=17, verbose_name='Teléfono')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='cbo.cbo', verbose_name='CBO')),
            ],
            options={
                'verbose_name': 'Rol Relevante de CBO',
                'verbose_name_plural': 'Roles Relevantes de CBO',
                'db_table': 'cbo_relevant_role',
                'ordering': ['predefined_role', 'custom_role'],
            },
        ),
    ]
