# Generated by Django 5.2.5 on 2025-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
