# Generated by Django 5.2.5 on 2025-10-23 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cbo', '0002_cbo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('file', models.FileField(help_text='Suba documentos como acta de constitución, RUT, etc. Máximo 10MB.', upload_to='cbo_documents/%Y/%m/%d/', verbose_name='Archivo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cbo.cbo', verbose_name='CBO')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento de CBO',
                'verbose_name_plural': 'Documentos de CBO',
                'db_table': 'cbo_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
