"""
Django settings for climas project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv() # Load variables from `.env` file.
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-1m)m1448nnqg7y=ht4j52(+@(=$19zz_6*9%dp7-407bv#&1%='
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'fallback-for-dev')
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(',')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

# Trust the proxy headers from nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# If using HTTPS, un comment the three following:
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

#AUTH_USER_MODEL = 'accounts.CustomUser'
AUTH_USER_MODEL = 'auth.User'
ADMIN_SITE_HEADER = "Climas Administration"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',

    'captcha',
    'django.contrib.humanize',

    'core.apps.CoreConfig',
    'common.apps.CommonConfig',
    'geo.apps.GeoConfig',
    'people.apps.PeopleConfig',
    'accounts.apps.AccountsConfig',
    'institutions.apps.InstitutionsConfig',
    'calls.apps.CallsConfig',
    'thematic_axes.apps.ThematicAxesConfig',
    'expressions.apps.ExpressionsConfig',
    'proposals.apps.ProposalsConfig',
    'evaluations.apps.EvaluationsConfig',
    'strategic_effects.apps.StrategicEffectsConfig',
    'products.apps.ProductsConfig',
    'budgets.apps.BudgetsConfig',
    'proponent_forms.apps.ProponentFormsConfig',
    'project_team.apps.ProjectTeamConfig',
    'experiences.apps.ExperiencesConfig',
    'antecedents.apps.AntecedentsConfig',
    'intersectionality.apps.IntersectionalityConfig',
    'cbo.apps.CboConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'climas.middleware.AutoLogoutMiddleware'
]

# Auto-logout after 15 minutes of inactivity
AUTO_LOGOUT_DELAY = 900  # 900 seconds = 15 minutes

# Expire session when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Expire after 15 minutes of inactivity
SESSION_COOKIE_AGE = 900  # same as AUTO_LOGOUT_DELAY

# Save session on every request (so last_activity updates reliably)
SESSION_SAVE_EVERY_REQUEST = True


ROOT_URLCONF = 'climas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'climas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ['DB_ENGINE'],
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': os.getenv('DB_CHARSET', 'utf8mb4'),  # default fallback
        },
        'ATOMIC_REQUESTS': False,
        'AUTOCOMMIT': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
FORCE_SCRIPT_NAME = '/climas'
STATIC_URL = '/climas/static/'
LOGIN_REDIRECT_URL = '/climas/accounts/profile/'
# named URL 
LOGIN_URL = 'accounts:login'
LOGOUT_REDIRECT_URL = 'accounts:login'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / "static"]
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:8080",
# ]
CSRF_TRUSTED_ORIGINS = os.environ['CSRF_TRUSTED_ORIGINS'].split(',')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RECAPTCHA_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
RECAPTCHA_DISABLE = False  # Set to True in production to disable