# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Persona')),
                ('document_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numero de documento')),
                ('first_name', models.CharField(max_length=32, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Segundo nombre')),
                ('first_last_name', models.CharField(max_length=32, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Segundo apellido')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, verbose_name='Genero')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.documenttype', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'person',
            },
        ),
    ]
