# Generated by Django 5.2.5 on 2025-09-11 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('calls', '0001_initial'),
        ('common', '0001_initial'),
        ('geo', '0001_initial'),
        ('thematic_axes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Rol')),
                ('project_title', models.TextField(verbose_name='Título del Proyecto')),
                ('problem', models.TextField(verbose_name='Descripción del Problema')),
                ('general_objective', models.TextField(verbose_name='Objetivo General')),
                ('methodology', models.TextField(verbose_name='Metodología')),
                ('funding_eligibility_acceptance', models.BooleanField(default=False, verbose_name='Aceptación de Elegibilidad para Financiamiento')),
                ('submission_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call', verbose_name='Convocatoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('implementation_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.country', verbose_name='País de Implementación')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado')),
                ('thematic_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thematic_axes.thematicaxis', verbose_name='Eje Temático')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Expresión de Interés',
                'verbose_name_plural': 'Expresiones de Interés',
                'db_table': 'expression',
                'ordering': ['-submission_datetime', '-created_at'],
            },
        ),
    ]
