# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('calls', '0001_initial'),
        ('common', '0001_initial'),
        ('geo', '0001_initial'),
        ('institutions', '0001_initial'),
        ('intersectionality', '0001_initial'),
        ('thematic_axes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Rol')),
                ('project_title', models.TextField(verbose_name='Título del Proyecto')),
                ('problem', models.TextField(verbose_name='Descripción del Problema')),
                ('general_objective', models.TextField(verbose_name='Objetivo General')),
                ('methodology', models.TextField(verbose_name='Metodología')),
                ('funding_eligibility_acceptance', models.BooleanField(default=False, verbose_name='Aceptación de Elegibilidad para Financiamiento')),
                ('submission_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call', verbose_name='Convocatoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('implementation_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.country', verbose_name='País de Implementación')),
                ('intersectionality_scopes', models.ManyToManyField(blank=True, related_name='expressions', to='intersectionality.intersectionalityscope', verbose_name='Ámbitos de Interseccionalidad')),
                ('primary_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expressions_as_primary', to='institutions.institution')),
                ('scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.scale', verbose_name='Escala del Presupuesto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado')),
                ('thematic_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thematic_axes.thematicaxis', verbose_name='Eje Temático')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Expresión de Interés',
                'verbose_name_plural': 'Expresiones de Interés',
                'db_table': 'expression',
                'ordering': ['-submission_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpressionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('file', models.FileField(help_text='Sube archivos como CV, cartas de apoyo, certificados. Máximo 10MB.', upload_to='expression_documents/%Y/%m/%d/', verbose_name='Archivo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='expressions.expression', verbose_name='Expresión de Interés')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento de Expresión',
                'verbose_name_plural': 'Documentos de Expresión',
                'db_table': 'expression_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
