# Generated by Django 5.2.5 on 2025-09-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0001_initial'),
        ('intersectionality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='intersectionality_scopes',
            field=models.ManyToManyField(blank=True, related_name='expressions', to='intersectionality.intersectionalityscope', verbose_name='Ámbitos de Interseccionalidad'),
        ),
    ]
