# Generated by Django 5.2.5 on 2025-10-02 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='primary_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expressions_as_primary', to='institutions.institution'),
        ),
    ]
