# Generated by Django 5.2.5 on 2025-10-23 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0002_cbo_is_active'),
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='community_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='cbo.cbo', verbose_name='Organización Comunitaria (CBO)'),
        ),
    ]
