# Generated by Django 5.2.5 on 2025-09-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_scale'),
        ('expressions', '0002_expression_primary_institution'),
        ('institutions', '0002_remove_institution_primary_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.scale', verbose_name='Escala del Presupuesto'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='primary_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expressions_as_primary', to='institutions.institution'),
            preserve_default=False,
        ),
    ]
