# Generated by Django 5.2.5 on 2025-09-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('expressions', '0002_expression_intersectionality_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('file', models.FileField(help_text='Sube archivos como CV, cartas de apoyo, certificados. Máximo 10MB.', upload_to='expression_documents/%Y/%m/%d/', verbose_name='Archivo')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='expressions.expression', verbose_name='Expresión de Interés')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser', verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento de Expresión',
                'verbose_name_plural': 'Documentos de Expresión',
                'db_table': 'expression_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
