# Generated by Django 5.2.5 on 2025-10-23 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0003_cbodocument'),
        ('expressions', '0002_expression_community_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='community_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressions', to='cbo.cbo', verbose_name='Organización Comunitaria (CBO)'),
        ),
    ]
