# Generated by Django 5.2.5 on 2025-10-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0003_alter_expression_community_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='past_projects_summary',
            field=models.TextField(blank=True, help_text='Hasta tres proyectos de los últimos 10 años. Máximo 60 palabras por proyecto (180 total).', verbose_name='Proyectos anteriores de la institución'),
        ),
    ]
