# Generated by Django 5.2.5 on 2025-09-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0004_expression_primary_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='primary_institution',
        ),
    ]
