# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expressions', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Presupuesto',
                'verbose_name_plural': 'Categorias de Presupuesto',
                'db_table': 'budget_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período de Presupuesto',
                'verbose_name_plural': 'Períodos de Presupuesto',
                'db_table': 'budget_period',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgets.budgetcategory', verbose_name='Categoría')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expressions.expression', verbose_name='Expresión de Interés')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgets.budgetperiod', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto (Expresión)',
                'verbose_name_plural': 'Ítems de Presupuesto (Expresión)',
                'db_table': 'budget_item',
                'ordering': ['category__name', 'period__order'],
                'unique_together': {('expression', 'category', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ProposalBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgets.budgetcategory', verbose_name='Categoría')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgets.budgetperiod', verbose_name='Período')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto (Propuesta)',
                'verbose_name_plural': 'Ítems de Presupuesto (Propuesta)',
                'db_table': 'proposal_budget_item',
                'ordering': ['category__name', 'period__order'],
                'abstract': False,
                'unique_together': {('proposal', 'category', 'period')},
            },
        ),
    ]
