# Generated by Django 5.2.5 on 2025-10-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Institucion')),
                ('is_active', models.BooleanField(default=True, help_text='Al deshabilitarse, no aparecera en las listas de seleccion.', verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Institucion',
                'verbose_name_plural': 'Tipos de institucion',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Departamento/Provincia')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de institucion')),
                ('acronym', models.CharField(blank=True, max_length=50, verbose_name='Acronym')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('tax_register_number', models.CharField(help_text='NUmero de registro tributario.', max_length=50, verbose_name='Numero de Registro Tributario')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Marque como inactivo en lugar de eliminar', verbose_name='Activa')),
                ('administrative_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_represented_institutions', to='people.person', verbose_name='Representante Administrativo')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='geo.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('legal_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_represented_institutions', to='people.person', verbose_name='Representante Legal')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutiontype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_institution_per_country')],
            },
        ),
    ]
