# Generated by Django 5.2.5 on 2025-09-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='primary_institution',
        ),
    ]
