# Generated by Django 5.2.5 on 2025-10-08 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Ejemplo: +573001234567', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (7 a 15 dígitos, puede incluir + al inicio).', regex='^\\+?\\d{7,15}$')], verbose_name='Teléfono'),
        ),
    ]
