# Generated by Django 5.2.5 on 2025-09-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_primary_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='primary_institution',
        ),
    ]
