# Generated by Django 5.2.5 on 2025-09-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('expressions', '0001_initial'),
        ('institutions', '0001_initial'),
        ('people', '0001_initial'),
        ('thematic_axes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('role', models.CharField(max_length=100, verbose_name='Rol en el Proyecto')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expressions.expression', verbose_name='Expresión de Interés')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Institución')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Persona')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado de Participación')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo de Proyecto',
                'verbose_name_plural': 'Miembros del Equipo de Proyecto',
                'db_table': 'project_team_member',
                'ordering': ['expression', 'role'],
                'unique_together': {('expression', 'person')},
            },
        ),
        migrations.CreateModel(
            name='InvestigatorThematicAxisAntecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('description', models.TextField(verbose_name='Descripción del Antecedente')),
                ('evidence_url', models.URLField(blank=True, verbose_name='URL de Evidencia')),
                ('thematic_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thematic_axes.thematicaxis', verbose_name='Eje Temático')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematic_antecedents', to='project_team.projectteammember', verbose_name='Miembro del Equipo')),
            ],
            options={
                'verbose_name': 'Antecedente en Eje Temático',
                'verbose_name_plural': 'Antecedentes en Ejes Temáticos',
                'db_table': 'investigator_thematic_antecedent',
            },
        ),
        migrations.CreateModel(
            name='InvestigatorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('condition_text', models.TextField(verbose_name='Condición')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Cumplida')),
                ('fulfillment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cumplimiento')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='project_team.projectteammember', verbose_name='Miembro del Equipo')),
            ],
            options={
                'verbose_name': 'Condición del Investigador',
                'verbose_name_plural': 'Condiciones de los Investigadores',
                'db_table': 'investigator_condition',
            },
        ),
    ]
