# Generated by Django 5.2.5 on 2025-10-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_team', '0001_initial'),
        ('thematic_axes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressioninvestigatorthematicantecedent',
            name='thematic_axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='thematic_axes.thematicaxis', verbose_name='Eje Temático'),
        ),
    ]
