# Generated by Django 5.2.5 on 2025-09-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('institutions', '0001_initial'),
        ('project_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteammember',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado de Participación'),
        ),
    ]
