# Generated by Django 5.2.5 on 2025-10-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_team', '0002_alter_expressioninvestigatorthematicantecedent_thematic_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinvestigatorthematicantecedent',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_thematic_antecedents', to='project_team.proposalteammember', verbose_name='Miembro del Equipo (Propuesta)'),
        ),
    ]
