# Generated by Django 5.2.5 on 2025-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_team', '0003_alter_proposalinvestigatorthematicantecedent_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionteammember',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='expressionteammember',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proposalteammember',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='proposalteammember',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
