# Generated by Django 5.2.5 on 2025-10-09 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_team', '0004_alter_expressionteammember_end_date_and_more'),
        ('thematic_axes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinvestigatorthematicantecedent',
            name='thematic_axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='thematic_axes.thematicaxis', verbose_name='Eje Temático'),
        ),
    ]
