# Generated by Django 5.2.5 on 2025-10-08 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('expressions', '0001_initial'),
        ('products', '0001_initial'),
        ('proposals', '0001_initial'),
        ('strategic_effects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo del Producto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('outcome', models.TextField(verbose_name='Resultado o impacto.')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalizacion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expressions.expression', verbose_name='Expresion de Interes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado')),
                ('strategic_effects', models.ManyToManyField(blank=True, related_name='%(class)s_products', to='strategic_effects.strategiceffect', verbose_name='Efectos Estrategicos')),
            ],
            options={
                'verbose_name': 'Producto de Expresión',
                'verbose_name_plural': 'Productos de Expresión',
                'db_table': 'expression_product',
            },
        ),
        migrations.CreateModel(
            name='ProposalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo del Producto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('outcome', models.TextField(verbose_name='Resultado o impacto.')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalizacion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal', verbose_name='Propuesta')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.status', verbose_name='Estado')),
                ('strategic_effects', models.ManyToManyField(blank=True, related_name='%(class)s_products', to='strategic_effects.strategiceffect', verbose_name='Efectos Estrategicos')),
            ],
            options={
                'verbose_name': 'Producto de Propuesta',
                'verbose_name_plural': 'Productos de Propuesta',
                'db_table': 'proposal_product',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
