# Generated by Django 5.2.5 on 2025-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_expressionproduct_proposalproduct_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionproduct',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AlterField(
            model_name='expressionproduct',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proposalproduct',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AlterField(
            model_name='proposalproduct',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
